version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=bareldan
      - POSTGRES_PASSWORD=qwer
      - POSTGRES_DB=bareldan
    ports:
      - '5432:5432'
    networks:
      - testing

  spring-app:
    image: server-java-spring-app
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    networks:
      - testing

  svelte-client:
    image: svelte
    ports:
      - '5173:5173'
    depends_on:
      - spring-app
    networks:
      - testing

networks:
  testing:
    driver: bridge
