version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=bareldan
      - POSTGRES_PASSWORD=qwer
      - POSTGRES_DB=bareldan
    ports:
      - '5432:5432'

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_DIR=/app  # Pass the app directory as an argument
    ports:
      - '8080:8080'
    depends_on:
      - postgres

