name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build server Docker image
        run: |
          docker build -t my-server-image .
          docker run -d --name my-server my-server-image

  run-tests:
    runs-on: ubuntu-latest
    needs: build-server
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "17"

      - name: Run tests
        run: ./gradlew test
